In [1]:
import numpy as np

**ndarray**

In [2]:
array_1D = np.array([1, 2, 3])

In [3]:
array_2D = np.array([[1, 2, 3],
                     [2, 3, 4]])

In [5]:
print(array_1D)
print(array_2D)

[1 2 3]
[[1 2 3]
 [2 3 4]]


**shape & dimension**

In [8]:
print(array_1D.shape)
print(array_2D.shape)

(3,)
(2, 3)


In [10]:
print(array_1D.ndim)
print(array_2D.ndim)

print(len(array_1D.shape))
print(len(array_2D.shape))

1
2
1
2


*<!> care*

In [31]:
array = np.array([[1, 2, 3]])

print(array.shape)
print(array.ndim)

(1, 3)
2


**type conversion**

In [21]:
array_float = np.array([1.0, 2.0, 3.0])

print(array_float.dtype)

float64


In [24]:
array_float = np.array(array_float, dtype=np.float32)

print(array_float.dtype)

float32


In [27]:
array_int = array_float.astype(np.int32)

print(array_int.dtype)

int32


In [28]:
array_int = array_int.astype(np.int16)

print(array_int.dtype)
print(array_int)

int16
[1 2 3]
