**Sorting**

In [1]:
import numpy as np

In [2]:
array = np.random.randint(0, 10, 6)
print(array)

[6 4 5 4 9 7]


*M1: np.sort()*

In [3]:
print(np.sort(array))
print(array)

[4 4 5 6 7 9]
[6 4 5 4 9 7]


*M2: .sort()*

In [4]:
array.sort()
print(array)

[4 4 5 6 7 9]


    *to descending order*

In [5]:
print(np.sort(array)[::-1])

[9 7 6 5 4 4]


    *2D array*

In [6]:
array = np.random.randint(0, 10, 6)
array = array.reshape(-1, 3)
print(array)

[[5 0 7]
 [9 0 5]]


In [7]:
print(np.sort(array, axis=0))
print(np.sort(array, axis=1))

[[5 0 5]
 [9 0 7]]
[[0 5 7]
 [0 5 9]]


**argsort()**

In [12]:
names = np.array(["sparrow", "goshawk", "eagle"])
scores = np.array([11, 17, 14])

print(np.argsort(scores))
print(names[np.argsort(scores)[::-1]])

[0 2 1]
['goshawk' 'eagle' 'sparrow']


**dot product**

In [19]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([1, 2, 1]).reshape(-1, 1)

print(np.dot(a, b))
print(a @ b)

[[ 8]
 [12]]
[[ 8]
 [12]]


**transpose**

In [29]:
print(a.shape)
a_transposed = a.transpose()
print(a_transposed, a_transposed.shape)

print(b.shape)
b_transposed = b.transpose()
print(b_transposed, b_transposed.shape)

c = np.array([1, 0, 1])
print(c.shape)
c_transposed = c.transpose()
print(c_transposed, c_transposed.shape)

(2, 3)
[[1 2]
 [2 3]
 [3 4]] (3, 2)
(3, 1)
[[1 2 1]] (1, 3)
(3,)
[1 0 1] (3,)
