In [1]:
import numpy as np

**ndarray**

In [2]:
array_1D = np.array([1, 2, 3])

In [3]:
array_2D = np.array([[1, 2, 3],
                     [2, 3, 4]])

In [4]:
print(array_1D)
print(array_2D)

[1 2 3]
[[1 2 3]
 [2 3 4]]


**shape & dimension**

In [5]:
print(array_1D.shape)
print(array_2D.shape)

(3,)
(2, 3)


In [6]:
print(array_1D.ndim)
print(array_2D.ndim)

print(len(array_1D.shape))
print(len(array_2D.shape))

1
2
1
2


*<!> care*

In [7]:
array = np.array([[1, 2, 3]])

print(array.shape)
print(array.ndim)

(1, 3)
2


**type conversion**

In [8]:
array_float = np.array([1.0, 2.0, 3.0])

print(array_float.dtype)

float64


In [9]:
array_float = np.array(array_float, dtype=np.float32)

print(array_float.dtype)

float32


In [10]:
array_int = array_float.astype(np.int32)

print(array_int.dtype)

int32


In [11]:
array_int = array_int.astype(np.int16)

print(array_int.dtype)
print(array_int)

int16
[1 2 3]


**frequently used initialization methods**

*arange*

In [12]:
array = np.arange(3, 10, 2)
print(array, array.dtype)

print(np.arange(10))

[3 5 7 9] int32
[0 1 2 3 4 5 6 7 8 9]


*zeros & ones*

In [13]:
array0 = np.zeros((2, 3))
array1 = np.ones((2, 3))

print(array0, array0.dtype)
print(array1, array1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64


In [14]:
array0 = np.zeros((2, 3), dtype=np.int32)
array1 = np.ones((2, 3), dtype=np.int32)

print(array0, array0.dtype)
print(array1, array1.dtype)

[[0 0 0]
 [0 0 0]] int32
[[1 1 1]
 [1 1 1]] int32


**reshape**

In [15]:
array = np.arange(6)

array = array.reshape(-1, 3)
print(array)

array = array.reshape(3, -1)
print(array)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [16]:
array = np.arange(12)

array = array.reshape(2, 2, 3)
print(array)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [17]:
array = array.reshape(-1, 1)
print(array.tolist())


[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]]


In [18]:
array = np.arange(3)
array_V = array.reshape(-1, 1)
print(array_V)

array_H = array.reshape(-1,)
print(array_H)

[[0]
 [1]
 [2]]
[0 1 2]


**Indexing**

*<M1> Single Indexing*

In [19]:
array = np.arange(1, 10)
print(array[3])

4


    *for 2D array*

In [20]:
array = array.reshape(-1, 3)
print(array)

print(array[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


*Slicing*

In [21]:
print(array[0:-1, :])

print(array[1, 1:])

print(array[1:, 1]) # <!> becomes a 1D array
print(array[1:, 1].shape)

[[1 2 3]
 [4 5 6]]
[5 6]
[5 8]
(2,)


    *Omit*

In [22]:
print(array[2]) # get the row

print(array[:2])

[7 8 9]
[[1 2 3]
 [4 5 6]]


*Fancy Indexing*

In [23]:
array = np.arange(16)
array = array.reshape(-1, 4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
print(array[list(range(0, 3, 2)), 1:])

print(array[list(range(0, 3, 2)), [0, 3]])

[[ 1  2  3]
 [ 9 10 11]]
[ 0 11]


*Boolean Indexing*

In [35]:
array = np.arange(16)
array = array.reshape(-1, 4)
array = array[[1, 3], :]
print(array)

[[ 4  5  6  7]
 [12 13 14 15]]


In [37]:
print(array > 6)
print(array[array > 6])

[[False False False  True]
 [ True  True  True  True]]
[ 7 12 13 14 15]
