In [42]:
import numpy as np
import pandas as pd

In [43]:
titanic_df = pd.read_csv("./data/titanic_train.csv")
# titanic_df = pd.read_csv("./data/titanic_train.csv", sep=",")
display(titanic_df)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [44]:
scores = np.random.randint(low=0, high=100, size=10)
passes = scores > 60

df = pd.DataFrame(scores, columns=["Score"])
df["Passed"] = passes

display(df)

Score  Passed
0     50   False
1     95    True
2     47   False
3     33   False
4     77    True
5     23   False
6     62    True
7     96    True
8     59   False
9     25   False

**get indices**

In [45]:
indices = df.index

display(indices)
print(indices.values)

RangeIndex(start=0, stop=10, step=1)

[0 1 2 3 4 5 6 7 8 9]


*pick some*

In [46]:
picks = [1, 3, 9]
picks = np.arange(1, 10, 2)

print(indices[picks].values) # pandas indices can be directly indexed
print(indices.values[picks])

print(indices[7])

[1 3 5 7 9]
[1 3 5 7 9]
7


*test opeerations on series*

In [47]:
score_sr = df["Score"]
print(score_sr)

print(score_sr.max(), max(score_sr))
print(score_sr.sum(), sum(score_sr))

0    50
1    95
2    47
3    33
4    77
5    23
6    62
7    96
8    59
9    25
Name: Score, dtype: int32
96 96
567 567


**reset_index()**

In [51]:
df_index_renewed = df.reset_index(inplace=False)

display(df_index_renewed)

index  Score  Passed
0      0     50   False
1      1     95    True
2      2     47   False
3      3     33   False
4      4     77    True
5      5     23   False
6      6     62    True
7      7     96    True
8      8     59   False
9      9     25   False

*example: .value_counts()*

In [67]:
Pclass_sr = titanic_df["Pclass"]
Pclass_counts = Pclass_sr.value_counts()
print(Pclass_counts, type(Pclass_counts))

Pclass_counts_1 = Pclass_counts.reset_index(inplace=False)
display(Pclass_counts_1, type(Pclass_counts_1)) # note data type is DataFrame, not Series

Pclass_counts_2 = Pclass_counts.reset_index(drop=True, inplace=False)
display(Pclass_counts_2, type(Pclass_counts_2)) # note data type is Series

3    491
1    216
2    184
Name: Pclass, dtype: int64 <class 'pandas.core.series.Series'>


index  Pclass
0      3     491
1      1     216
2      2     184

pandas.core.frame.DataFrame

0    491
1    216
2    184
Name: Pclass, dtype: int64

pandas.core.series.Series

*common use*

In [71]:
Pclass_counts = titanic_df["Pclass"].value_counts().reset_index()
Pclass_counts.rename(columns={"index":"Pclass #", "Pclass":"Pclass counts"}, inplace=True)

display(Pclass_counts)

Pclass #  Pclass counts
0         3            491
1         1            216
2         2            184