**L067_SVD_basics.ipynb**

2024 JUN 06

Tershire

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# demonstration

## part 1: full

### data

In [2]:
np.random.seed(121)

A = np.random.randn(4, 4)

In [3]:
print(f"A:\n{np.round(A, 3)}")

A:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


### perform SVD

In [4]:
U, sigmas, V_T = np.linalg.svd(A)

In [5]:
print(U.shape, sigmas.shape, V_T.shape, '\n')

print(f"U:\n{np.round(U, 3)}\n")
print(f"sigmas:\n{np.round(sigmas, 3)}\n")
print(f"V^T:\n{np.round(V_T, 3)}")

(4, 4) (4,) (4, 4) 

U:
[[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]

sigmas:
[3.423 2.023 0.463 0.079]

V^T:
[[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


### restoration

In [6]:
Sigma = np.diag(sigmas)
A_restored = np.dot(U, np.dot(Sigma, V_T))

In [7]:
print(f"A:\n{np.round(A, 3)}\n")
print(f"A_restored:\n{np.round(A_restored, 3)}")

A:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]

A_restored:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


## part 2: compact

### data having heavy correlation

In [8]:
B = A
B[1] = A[0] + A[2]
B[3] = A[0]

In [9]:
print(f"B:\n{np.round(B, 3)}")

B:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.226  0.345  1.136 -1.767]
 [-0.014  0.63   1.71  -1.327]
 [-0.212 -0.285 -0.574 -0.44 ]]


### perform SVD

In [10]:
U, sigmas, V_T = np.linalg.svd(A)

In [11]:
print(U.shape, sigmas.shape, V_T.shape, '\n')

print(f"U:\n{np.round(U, 3)}\n")
print(f"sigmas:\n{np.round(sigmas, 3)}\n")
print(f"V^T:\n{np.round(V_T, 3)}")

(4, 4) (4,) (4, 4) 

U:
[[ 0.045  0.631 -0.375 -0.678]
 [-0.683  0.366  0.63  -0.053]
 [-0.728 -0.265 -0.63   0.053]
 [ 0.045  0.631 -0.255  0.731]]

sigmas:
[3.062 1.258 0.    0.   ]

V^T:
[[ 0.048 -0.235 -0.676  0.696]
 [-0.275 -0.318 -0.605 -0.676]
 [ 0.05  -0.918  0.388  0.064]
 [ 0.959 -0.032 -0.16  -0.232]]


### restoration

In [12]:
n = sum(sigmas > 1E-3)
print("n:", n)

Sigma = np.diag(sigmas[:n])
B_restored = np.dot(U[:, :n], np.dot(Sigma, V_T[:n]))

n: 2


In [13]:
print(f"B:\n{np.round(B, 3)}\n")
print(f"B_restored:\n{np.round(B_restored, 3)}\n")

B:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.226  0.345  1.136 -1.767]
 [-0.014  0.63   1.71  -1.327]
 [-0.212 -0.285 -0.574 -0.44 ]]

B_restored:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.226  0.345  1.136 -1.767]
 [-0.014  0.63   1.71  -1.327]
 [-0.212 -0.285 -0.574 -0.44 ]]



## part 3: truncated

### data

In [50]:
np.random.seed(121)

A = np.random.randn(4, 4)

In [51]:
print(f"A:\n{np.round(A, 3)}")

A:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


### perform SVD

In [52]:
import scipy

**full**

In [62]:
U, sigmas, V_T = scipy.linalg.svd(A, full_matrices=False)

In [63]:
print(U.shape, sigmas.shape, V_T.shape, '\n')

print(f"U:\n{np.round(U, 3)}\n")
print(f"sigmas:\n{np.round(sigmas, 3)}\n")
print(f"V^T:\n{np.round(V_T, 3)}")

(4, 4) (4,) (4, 4) 

U:
[[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]

sigmas:
[3.423 2.023 0.463 0.079]

V^T:
[[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


**truncated**

In [64]:
n = 2
print("n:", n)

U_trc, sigmas_trc, V_T_trc = scipy.sparse.linalg.svds(A, k=n)

n: 2


In [71]:
print(U_trc.shape, sigmas_trc.shape, V_T_trc.shape, '\n')

print(f"U (truncated):\n{np.round(U_trc, 3)}\n")
print(f"sigmas (truncated):\n{np.round(np.flip(sigmas_trc), 3)}\n")
print(f"V^T (truncated):\n{np.round(V_T_trc, 3)}")

(4, 2) (2,) (2, 4) 

U (truncated):
[[-0.318  0.079]
 [ 0.787 -0.383]
 [ 0.022 -0.656]
 [-0.529 -0.645]]

sigmas (truncated):
[3.423 2.023]

V^T (truncated):
[[-0.2    0.562  0.37   0.712]
 [-0.041 -0.224 -0.786  0.574]]


### approximate restoration

**using numpy**

In [66]:
Sigma = np.diag(sigmas[:n])
A_restored = np.dot(U[:, :n], np.dot(Sigma, V_T[:n]))

In [67]:
print(f"A:\n{np.round(B, 3)}\n")
print(f"A_restored:\n{np.round(A_restored, 3)}\n")

A:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.226  0.345  1.136 -1.767]
 [-0.014  0.63   1.71  -1.327]
 [-0.212 -0.285 -0.574 -0.44 ]]

A_restored:
[[ 0.118 -0.422 -0.451 -0.303]
 [-0.265  1.188  1.62   0.38 ]
 [ 0.083  0.528  1.784 -1.258]
 [ 0.305 -0.107  1.341 -2.03 ]]



**using scipy**

In [68]:
Sigma_trc = np.diag(sigmas_trc)
A_restored = np.dot(U_trc, np.dot(Sigma_trc, V_T_trc))

In [69]:
print(f"A:\n{np.round(B, 3)}\n")
print(f"A_restored:\n{np.round(A_restored, 3)}\n")

A:
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.226  0.345  1.136 -1.767]
 [-0.014  0.63   1.71  -1.327]
 [-0.212 -0.285 -0.574 -0.44 ]]

A_restored:
[[ 0.118 -0.422 -0.451 -0.303]
 [-0.265  1.188  1.62   0.38 ]
 [ 0.083  0.528  1.784 -1.258]
 [ 0.305 -0.107  1.341 -2.03 ]]

