In [14]:
# 2023 OCT 19

In [16]:
import numpy as np
import pandas as pd

**label**

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
birds = ["pigeon", "eagle", "hawk", "eagle", "sparrow", "pigeon", "pigeon"]

In [12]:
# create object
encoder = LabelEncoder()

# fit: get unique entities and assign label
encoder.fit(birds)

# transform: encode:
labels = encoder.transform(birds)

#
print(labels)

[2 0 1 0 3 2 2]


In [13]:
# check assignment
print(encoder.classes_)

# inverse transform
print(encoder.inverse_transform([3, 3, 3, 2, 1, 2, 0]))

['eagle' 'hawk' 'pigeon' 'sparrow']
['sparrow' 'sparrow' 'sparrow' 'pigeon' 'hawk' 'pigeon' 'eagle']


**one-hot**

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
birds = ["pigeon", "eagle", "hawk", "eagle", "sparrow", "pigeon", "pigeon"]

In [19]:
# -> 2D ndarray
birds = np.array(birds).reshape(-1, 1)
print(birds.shape)

(7, 1)


In [24]:
# create object
encoder = OneHotEncoder()

# fit: get unique entities and assign label
encoder.fit(birds)

# transform: encode:
labels = encoder.transform(birds)

#
print(labels) 
print(type(labels))  # sparse matrix

  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 3)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
<class 'scipy.sparse._csr.csr_matrix'>


In [26]:
# sparse matrix -> dense matrix
print(labels.toarray())

print(labels.shape)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
(7, 4)


**<!> fit & transform altogether <!>**

In [28]:
# labels = encoder.fit_transform(birds)

**one-hot: easier method using pandas**

In [30]:
birds = ["pigeon", "eagle", "hawk", "eagle", "sparrow", "pigeon", "pigeon"]

bird_df = pd.DataFrame({"bird": birds})

display(pd.get_dummies(bird_df))

bird_eagle  bird_hawk  bird_pigeon  bird_sparrow
0           0          0            1             0
1           1          0            0             0
2           0          1            0             0
3           1          0            0             0
4           0          0            0             1
5           0          0            1             0
6           0          0            1             0